# Funding options for QuizLink
# You can enable different funding options here

github: # Replace with up to 4 GitHub Sponsors usernames
patreon: # Replace with a single Patreon username
open_collective: # Replace with a single Open Collective username
ko_fi: # Replace with a single Ko-fi username
tidelift: # Replace with a single Tidelift platform-name/package-name
community_bridge: # Replace with a single Community Bridge project-name
liberapay: # Replace with a single Liberapay username
issuehunt: # Replace with a single IssueHunt username
custom: # Replace with up to 4 custom sponsorship URLs

